name = "kelbyone-pages"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[[r2_buckets]]
binding = "GRID_EDIT_UPLOADS"
bucket_name = "grid-edit-uploads"
